


/*
   -- Senior Design --
   
   To compile this code using RemoteXY library 4.1.4 or later version 
   download by link http://remotexy.com/en/library/
   To connect using RemoteXY mobile app by link http://remotexy.com/en/download/                   
     - for ANDROID 4.16.02 or later version;
     - for iOS 1.13.1 or later version;
    
   To interact with the GUI, please refer to the manual: 
   https://remotexy.com/ru/help/code/interaction/

   This source code was automatically generated by the RemoteXY editor and 
   is an example for the RemoteXY library. 
   Licensed under the MIT License. See the LICENSE file in the RemoteXY library
   root (https://github.com/RemoteXY/RemoteXY-Arduino-library) for full license 
   details.             
*/


//////////////////////////////////////////////
//        RemoteXY include library          //
//////////////////////////////////////////////


// you can enable debug logging to Serial at 115200
//#define REMOTEXY__DEBUGLOG    


// RemoteXY select connection mode and include library
#define REMOTEXY_MODE__WIFI_POINT


#include <ESP8266WiFi.h>


// RemoteXY connection settings 
#define REMOTEXY_WIFI_SSID "RemoteXY"
#define REMOTEXY_WIFI_PASSWORD "12345678"
#define REMOTEXY_SERVER_PORT 6377


#include <RemoteXY.h>
#include <Servo.h>


// RemoteXY GUI configuration  
#pragma pack(push, 1)  
uint8_t RemoteXY_CONF[] =   // 153 bytes
  { 255,4,0,1,0,146,0,19,0,0,0,0,31,2,106,200,200,84,1,1,
  5,0,4,8,62,7,86,26,23,10,46,48,6,26,10,9,48,57,57,51,
  5,18,18,48,4,26,31,65,117,116,111,0,31,77,97,110,117,97,108,0,
  4,15,59,5,110,171,24,10,46,48,6,26,4,34,33,7,86,76,32,59,
  11,128,2,26,74,67,17,21,24,130,8,40,10,92,2,30,37,64,87,111,
  111,100,0,37,64,77,101,116,97,108,0,37,64,87,97,115,116,101,0,37,
  64,72,32,87,97,115,116,101,0,37,64,72,32,67,111,110,116,97,105,110,
  101,114,115,0,37,64,69,108,101,99,116,114,0 };
  
// this structure defines all the variables and events of your control interface 
struct {

    // input variables
  int8_t slider_01; // from -100 to 100
  uint8_t pushSwitch_01; // =1 if state is ON, else =0, from 0 to 1
  int8_t slider_02; // from -100 to 100
  int8_t slider_03; // from 0 to 100

    // output variables
  uint8_t strings_01; // from 0 to 6

    // other variable
  uint8_t connect_flag;  // =1 if wire connected, else =0

} RemoteXY;   
#pragma pack(pop)
 
/////////////////////////////////////////////
//           END RemoteXY include          //
/////////////////////////////////////////////


struct Motor {
  const char* name;
  uint8_t speedPin;
  uint8_t dir1Pin;
  uint8_t dir2Pin;
  int duty;
  bool dirState1;
  bool dirState2;


// Initialize
  void begin() {
    pinMode(speedPin, OUTPUT);
    pinMode(dir1Pin, OUTPUT);
    pinMode(dir2Pin, OUTPUT);
  }


// Update PWM and direction
  void update() {
    if (duty < 0) {
      dirState1 = LOW;
      dirState2 = !dirState1;
    }
    if (duty > 0) {
      dirState1 = HIGH;
      dirState2 = !dirState1;
    }
    if (abs(duty) < 10) {
      dirState1 = LOW;
      dirState2 = LOW;
    }


    digitalWrite(dir1Pin, dirState1);
    digitalWrite(dir2Pin, dirState2);
    analogWrite(speedPin, abs(duty));
    Serial.printf("%s Duty: %d\n", name, duty);
  }
};


//Servo servo1;
//Servo servo2;


// Motor name = {name, speedPin, dir1Pin, dir2Pin, duty}
Motor motorL = {"L",  12, 14, 2};
Motor motorR = {"R",  5,  4,  0};
// int servo1Pin = 13;
// int servo2Pin = 10;


void setup()
{
  Serial.begin(115200);
  Serial.println("Starting ESP8266...");
  
  RemoteXY_Init ();
  Serial.println("RemoteXY Initialized.");
  
  motorL.begin();
  motorR.begin();
  
  // Wait for WiFi connection
  Serial.println("Waiting for WiFi connection...");
  delay(3000);
  
  // Check WiFi status
  if (WiFi.status() == WL_CONNECTED) {
    Serial.println("WiFi Connected!");
    Serial.print("IP Address: ");
    Serial.println(WiFi.localIP());
  } else {
    Serial.println("WiFi Connection Failed!");
    Serial.print("Status: ");
    Serial.println(WiFi.status());
  }
  
  //servo1.attach(servo1Pin);
  //servo2.attach(servo2Pin);
}


void loop()
{
  RemoteXY_Handler ();
  
  // Check WiFi connection status
  static unsigned long lastWiFiCheck = 0;
  if (millis() - lastWiFiCheck > 5000) { // Check every 5 seconds
    lastWiFiCheck = millis();
    if (WiFi.status() != WL_CONNECTED) {
      Serial.println("WiFi Disconnected!");
    } else {
      Serial.println("WiFi Connected - IP: " + WiFi.localIP().toString());
    }
  }
  
  int slider_llimit = -100;
  int slider_ulimit = 100;
  int speedLimit = 255;
  
  // Motor control based on mode
  if (RemoteXY.pushSwitch_01 == 0) {
    // Manual mode
    motorL.duty = map(RemoteXY.slider_01, slider_llimit, slider_ulimit, -speedLimit, speedLimit);
    motorR.duty = map(RemoteXY.slider_02, slider_llimit, slider_ulimit, -speedLimit, speedLimit);
  } else {
    // Auto mode
    // TODO: Implement automatic control logic
    motorL.duty = 0;
    motorR.duty = 0;
  }
  
  motorL.update();
  motorR.update();

  // Servo control using slider_03 (0 to 100)
  //int servoAngle = map(RemoteXY.slider_03, 0, 100, 0, 180);
  //servo1.write(servoAngle);
}